// ═══════════════════════════════════════════════════════════════
// KelionAI — Export Routes (PDF, XLSX, PPTX)
// Generates downloadable files from brain-stored documents
// ═══════════════════════════════════════════════════════════════
'use strict';

const express = require('express');
const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const logger = require('../logger');

const router = express.Router();

// GET /api/export/pdf?key=doc:my_document
router.get('/pdf', async (req, res) => {
  try {
    const { getUserFromToken, supabaseAdmin } = req.app.locals;
    if (!supabaseAdmin) return res.status(500).json({ error: 'Database not connected' });
    const user = await getUserFromToken(req);
    const key = req.query.key;
    if (!key) return res.status(400).json({ error: 'Missing key parameter' });

    const { data } = await supabaseAdmin
      .from('user_preferences')
      .select('value')
      .eq('user_id', user?.id || 'system')
      .eq('key', key)
      .maybeSingle();
    if (!data?.value) return res.status(404).json({ error: 'Document not found' });

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const filename = (data.value.title || 'document').replace(/[^a-zA-Z0-9]/g, '_') + '.pdf';

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    doc.pipe(res);

    // Header
    doc
      .fontSize(22)
      .font('Helvetica-Bold')
      .text(data.value.title || 'Document', { align: 'center' });
    doc.moveDown(0.5);
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#666')
      .text(`Generated by KelionAI • ${new Date().toLocaleDateString('ro-RO')}`, { align: 'center' });
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#6366F1');
    doc.moveDown(1);

    // Content
    doc.fontSize(12).font('Helvetica').fillColor('#111');
    const content = data.value.content || JSON.stringify(data.value, null, 2);
    // Handle sections if present
    if (data.value.sections && typeof data.value.sections === 'object') {
      for (const [section, entries] of Object.entries(data.value.sections)) {
        doc.fontSize(16).font('Helvetica-Bold').text(section);
        doc.moveDown(0.3);
        const items = Array.isArray(entries) ? entries : [entries];
        for (const entry of items) {
          const text = typeof entry === 'string' ? entry : entry.content || JSON.stringify(entry);
          doc.fontSize(11).font('Helvetica').text(text, { lineGap: 3 });
          doc.moveDown(0.5);
        }
        doc.moveDown(0.5);
      }
    } else {
      doc.text(content, { lineGap: 4 });
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999').text('KelionAI — kelionai.app', { align: 'center' });

    doc.end();
    logger.info({ component: 'Export', format: 'pdf', key }, 'PDF exported');
  } catch (e) {
    logger.error({ component: 'Export', err: e.message }, 'PDF export failed');
    if (!res.headersSent) res.status(500).json({ error: e.message });
  }
});

// GET /api/export/xlsx?key=spreadsheet:my_data
router.get('/xlsx', async (req, res) => {
  try {
    const { getUserFromToken, supabaseAdmin } = req.app.locals;
    if (!supabaseAdmin) return res.status(500).json({ error: 'Database not connected' });
    const user = await getUserFromToken(req);
    const key = req.query.key;
    if (!key) return res.status(400).json({ error: 'Missing key parameter' });

    const { data } = await supabaseAdmin
      .from('user_preferences')
      .select('value')
      .eq('user_id', user?.id || 'system')
      .eq('key', key)
      .maybeSingle();
    if (!data?.value) return res.status(404).json({ error: 'Spreadsheet not found' });

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'KelionAI';
    workbook.created = new Date();
    const sheet = workbook.addWorksheet(data.value.title || 'Sheet1');

    // Add columns
    if (data.value.columns && data.value.columns.length > 0) {
      sheet.columns = data.value.columns.map((c) => ({
        header: c,
        key: c.toLowerCase().replace(/\s+/g, '_'),
        width: 18,
      }));
      // Style header
      sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
      sheet.getRow(1).fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF6366F1' },
      };
    }

    // Add data rows if present
    if (data.value.rows && Array.isArray(data.value.rows)) {
      for (const row of data.value.rows) {
        sheet.addRow(row);
      }
    } else if (data.value.data && typeof data.value.data === 'string') {
      // Parse CSV-like data
      const lines = data.value.data.split('\n').filter((l) => l.trim());
      for (const line of lines) {
        sheet.addRow(line.split(',').map((c) => c.trim()));
      }
    }

    const filename = (data.value.title || 'spreadsheet').replace(/[^a-zA-Z0-9]/g, '_') + '.xlsx';
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    await workbook.xlsx.write(res);
    res.end();
    logger.info({ component: 'Export', format: 'xlsx', key }, 'XLSX exported');
  } catch (e) {
    logger.error({ component: 'Export', err: e.message }, 'XLSX export failed');
    if (!res.headersSent) res.status(500).json({ error: e.message });
  }
});

// GET /api/export/pptx?key=presentation:my_slides
// Returns structured JSON — frontend can render as slides
router.get('/pptx', async (req, res) => {
  try {
    const { getUserFromToken, supabaseAdmin } = req.app.locals;
    if (!supabaseAdmin) return res.status(500).json({ error: 'Database not connected' });
    const user = await getUserFromToken(req);
    const key = req.query.key;
    if (!key) return res.status(400).json({ error: 'Missing key parameter' });

    const { data } = await supabaseAdmin
      .from('user_preferences')
      .select('value')
      .eq('user_id', user?.id || 'system')
      .eq('key', key)
      .maybeSingle();
    if (!data?.value) return res.status(404).json({ error: 'Presentation not found' });
    res.json({ presentation: data.value });
  } catch (e) {
    logger.error({ component: 'Export', err: e.message }, 'PPTX export failed');
    res.status(500).json({ error: e.message });
  }
});

// GET /api/export/history — export conversation history
router.get('/history', async (req, res) => {
  try {
    const { getUserFromToken, supabaseAdmin } = req.app.locals;
    const user = await getUserFromToken(req);
    if (!user) return res.status(401).json({ error: 'Authentication required' });
    if (!supabaseAdmin) return res.status(500).json({ error: 'Database not connected' });

    const { data } = await supabaseAdmin
      .from('conversations')
      .select('id, created_at, messages_text')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .limit(50);
    res.json({ conversations: data || [], formats: ['pdf', 'xlsx', 'json'] });
  } catch (e) {
    logger.error({ component: 'Export', err: e.message }, 'History export failed');
    res.status(500).json({ error: e.message });
  }
});

/**
 * undefined
 * @returns {*}
 */
module.exports = router;
