// Patch voice.js: ElevenLabs DOAR clonare, OpenAI TTS primar, Google Cloud fallback
const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'server', 'routes', 'voice.js');
const lines = fs.readFileSync(file, 'utf-8').split('\n');

// Lines 1-102 (idx 0-101): before TTS engines — KEEP
const before = lines.slice(0, 102);
// Lines 202-268 (idx 201-267): Google Cloud TTS — KEEP (update comment)
const googleCloud = lines.slice(201, 268);
// Lines 305+ (idx 304+): dev fallback + alignment + listen + lipsync — KEEP
const after = lines.slice(304);

// Update Google Cloud comment: TRY 1 → TRY 2
googleCloud[1] = googleCloud[1].replace('TRY 1:', 'TRY 2:');

const newTTS = [
  '    let buf = null;',
  '    let alignment = null;',
  "    let ttsEngine = 'OpenAI';",
  '',
  '    // ══════════════════════════════════════════════════════════',
  '    // TRY 0: ElevenLabs — DOAR pentru voci clonate',
  '    // Vocile standard folosesc OpenAI TTS. ElevenLabs se foloseste',
  '    // exclusiv cand userul are o voce clonata activa.',
  '    // ══════════════════════════════════════════════════════════',
  '    const ELEVEN_KEY = process.env.ELEVENLABS_API_KEY;',
  '    if (ELEVEN_KEY && user && supabaseAdmin) {',
  '      try {',
  '        const { data: cv } = await supabaseAdmin',
  "          .from('cloned_voices')",
  "          .select('elevenlabs_voice_id')",
  "          .eq('user_id', user.id)",
  "          .eq('is_active', true)",
  '          .limit(1)',
  '          .single();',
  '',
  '        if (cv?.elevenlabs_voice_id) {',
  '          const elCtrl = new AbortController();',
  '          const elTimer = setTimeout(() => elCtrl.abort(), 15000);',
  "          const elModel = MODELS.ELEVENLABS_MODEL || 'eleven_v3';",
  '',
  '          const elBody = {',
  '            text,',
  '            model_id: elModel,',
  '            voice_settings: {',
  '              stability: 0.5,',
  '              similarity_boost: 0.75,',
  '              style: 0.45,',
  '              use_speaker_boost: true,',
  '            },',
  '          };',
  '',
  '          const elResp = await fetch(`${API_ENDPOINTS.ELEVENLABS}/text-to-speech/${cv.elevenlabs_voice_id}/with-timestamps`, {',
  "            method: 'POST',",
  '            signal: elCtrl.signal,',
  '            headers: {',
  "              'Content-Type': 'application/json',",
  "              'xi-api-key': ELEVEN_KEY,",
  "              Accept: 'application/json',",
  '            },',
  '            body: JSON.stringify(elBody),',
  '          });',
  '          clearTimeout(elTimer);',
  '',
  '          if (elResp.ok) {',
  '            const elData = await elResp.json();',
  '            if (elData.audio_base64) {',
  "              buf = Buffer.from(elData.audio_base64, 'base64');",
  "              ttsEngine = 'ElevenLabs-Clone';",
  '',
  '              if (elData.alignment) {',
  '                alignment = {',
  '                  characters: elData.alignment.characters || [],',
  '                  character_start_times_seconds: elData.alignment.character_start_times_seconds || [],',
  '                  character_end_times_seconds: elData.alignment.character_end_times_seconds || [],',
  '                };',
  '              }',
  '              logger.info(',
  '                { component: \'Speak\', voice: cv.elevenlabs_voice_id, model: elModel, hasAlignment: !!alignment },',
  "                'ElevenLabs cloned voice TTS OK'",
  '              );',
  '            }',
  '          } else {',
  "            const errText = await elResp.text().catch(() => '');",
  '            logger.warn(',
  '              { component: \'Speak\', status: elResp.status, err: errText.substring(0, 200) },',
  "              'ElevenLabs cloned voice failed, falling through to OpenAI'",
  '            );',
  '          }',
  '        }',
  '      } catch (e) {',
  "        logger.debug({ component: 'Speak', err: e.message }, 'Cloned voice check failed, using OpenAI TTS');",
  '      }',
  '    }',
  '',
  '    // ══════════════════════════════════════════════════════════',
  '    // TRY 1: OpenAI TTS (PRIMAR — gpt-4o-mini-tts voci native)',
  '    // ══════════════════════════════════════════════════════════',
  "    let openaiErr = 'no OPENAI_API_KEY';",
  '    if (!buf && process.env.OPENAI_API_KEY) {',
  '      try {',
  '        const oaiCtrl = new AbortController();',
  '        const oaiTimer = setTimeout(() => oaiCtrl.abort(), 12000);',
  "        const openaiVoice = avatar === 'kira' ? 'nova' : 'onyx';",
  "        const r2 = await fetch(API_ENDPOINTS.OPENAI + '/audio/speech', {",
  "          method: 'POST',",
  '          signal: oaiCtrl.signal,',
  '          headers: {',
  "            'Content-Type': 'application/json',",
  "            Authorization: 'Bearer ' + process.env.OPENAI_API_KEY,",
  '          },',
  '          body: JSON.stringify({',
  '            model: MODELS.OPENAI_TTS,',
  '            input: text,',
  '            voice: openaiVoice,',
  "            response_format: 'mp3',",
  '          }),',
  '        });',
  '        clearTimeout(oaiTimer);',
  '        if (r2.ok) {',
  '          buf = Buffer.from(await r2.arrayBuffer());',
  "          ttsEngine = 'OpenAI';",
  '          logger.info(',
  "            { component: 'Speak', voice: openaiVoice, model: MODELS.OPENAI_TTS, avatar },",
  "            'OpenAI TTS OK'",
  '          );',
  '        } else {',
  "          openaiErr = r2.status + ': ' + (await r2.text().catch(() => '')).substring(0, 200);",
  "          logger.warn({ component: 'Speak', status: r2.status, error: openaiErr }, 'OpenAI TTS failed, trying Google Cloud');",
  '        }',
  '      } catch (e) {',
  '        openaiErr = e.message;',
  "        logger.warn({ component: 'Speak', err: e.message }, 'OpenAI TTS error, trying Google Cloud');",
  '      }',
  '    }',
  '',
];

const result = [...before, ...newTTS, ...googleCloud, '', ...after];
fs.writeFileSync(file, result.join('\n'));
console.log('voice.js patched: ElevenLabs=clonare, OpenAI TTS=primar, Google Cloud=fallback');
console.log('Lines: ' + lines.length + ' -> ' + result.length);
